markdown: kramdown
permalink: pretty

collections:
  issues:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: "notes"
    values:
      layout: notes
  - scope:
      path: ""
      type: issues
    values:
      layout: issue